version: '3.8'

networks:
  my-net:
    driver: bridge

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-net


  price_generator:
    image: price_generator
    environment:
      REDIS_ADDR: "redis:6379"
    networks:
      - my-net


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "vitalijprokopenya"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5431:5432"
    networks:
      - my-net



  order_service:
    image: order:latest
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      REDIS_ADDR: "redis:6379"
    ports:
     - '50004:50004'
    networks:
      - my-net


  position_service:
    image: position:latest
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    ports:
      - '50005:50005'
    networks:
      - my-net


  broker_client:
    image: client:latest
    networks:
      - my-net
