apiVersion: v1
kind: Service
metadata:
  name: dev-client-service
  labels:
    app: dev-client-service
spec:
  type: NodePort
  ports:
    - port: 321
      protocol: TCP
      targetPort: 321
  selector:
    app: dev-client-service